import {StyleSheet} from 'react-native';
import scale from '../../assets/constants/responsive';
import CUSTOM_COLOR from '../../assets/constants/colors';
import FONT_FAMILY from '../../assets/constants/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  titleContainer: {
    top: scale(30),
    height: scale(40),
    width: '100%',
    position: 'absolute',
  },
  textTitle: {
    marginTop: scale(7),
    fontSize: scale(23),
    fontFamily: FONT_FAMILY.SFProTextBold,
    color: CUSTOM_COLOR.Black,
    height: '100%',
    justifyContent: 'center',
    alignSelf: 'center',
    position: 'absolute',
  },
  backButton: {
    height: '100%',
    width: scale(50),
    justifyContent: 'center',
    position: 'absolute',
    left: scale(60),
    marginTop: scale(3),
  },
  iconBack: {
    justifyContent: 'center',
    alignSelf: 'center',
  },
  SelectionText: {
    color: CUSTOM_COLOR.White,
    fontSize: 15,
    fontFamily: FONT_FAMILY.SFProTextBold,
    alignSelf: 'center',
  },
  buttonSelection: {
    width: scale(314),
    height: scale(70),
    borderRadius: 30,
    backgroundColor: CUSTOM_COLOR.Vermilion,
    bottom: scale(41),
    justifyContent: 'center',
    alignSelf: 'center',
    position: 'absolute',
  },
  formText: {
    fontFamily: FONT_FAMILY.AbelRe,
    width: scale(160),
    height: scale(50),
    top: scale(105),
    left: scale(80),
    fontSize: scale(43),
    color: CUSTOM_COLOR.Black,
  },
  text1: {
    height: scale(30),
    color: CUSTOM_COLOR.Black,
    fontSize: scale(17),
    marginTop: scale(133),
    marginLeft: scale(80),
  },
  changeButton: {
    height: scale(22),
    width: scale(70),
    marginTop: scale(185),
    marginLeft: scale(385),
    position: 'absolute',
  },
  changeButtonText: {
    justifyContent: 'center',
    alignSelf: 'center',
    fontSize: scale(15),
    color: CUSTOM_COLOR.GoldDrop,
  },
  addressContainer: {
    width: scale(375),
    height: scale(160),
    backgroundColor: CUSTOM_COLOR.White,
    marginTop: scale(21),
    alignSelf: 'center',
    borderRadius: 20,
  },
  address: {
    height: '100%',
    width: '80%',
    alignSelf: 'center',
  },
  addressText: {
    padding: scale(6.5),
    color: CUSTOM_COLOR.Black,
    fontSize: scale(17),
    marginTop: scale(7),
  },
  methodText: {
    marginTop: scale(35),
    color: CUSTOM_COLOR.Black,
    fontSize: scale(17),
    marginLeft: scale(80),
  },
  doorOrPickupContainer: {
    alignSelf: 'center',
    height: '100%',
    width: '70%',
    marginLeft: scale(10),
  },
  doorOrPickupText: {
    paddingVertical: scale(22),
    color: CUSTOM_COLOR.Black,
    fontSize: scale(17),
    marginTop: scale(3),
  },
  paymentContainer: {
    width: scale(375),
    height: scale(200),
    backgroundColor: CUSTOM_COLOR.White,
    marginTop: scale(21),
    alignSelf: 'center',
    borderRadius: 20,
  },
  payment: {
    height: '100%',
    width: '70%',
    alignSelf: 'center',
    marginLeft: scale(25),
  },
  paymentText: {
    color: CUSTOM_COLOR.Black,
    fontSize: scale(17),
    marginTop: scale(26),
    marginLeft: scale(55),
  },
  paymentTextView: {
    width: '100%',
    height: scale(75),
  },
  iconView: {
    width: scale(45),
    height: scale(45),
    marginTop: scale(-33),
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  totalContainer: {
    width: '100%',
    height: scale(45),
    marginTop: scale(20),
    justifyContent: 'center',
  },
  total: {
    fontSize: scale(17),
    marginLeft: scale(80),
    color: CUSTOM_COLOR.Black,
  },
  cost: {
    fontSize: scale(22),
    marginLeft: scale(400),
    color: CUSTOM_COLOR.Black,
    position: 'absolute',
  },
  backgroundLeft: {
    height: '100%',
    width: '20%',
    flexDirection: 'row',
    position: 'absolute',
  },
  backgroundRight: {
    height: '100%',
    width: '80%',
    marginLeft: scale(30),
    alignSelf: 'flex-start',
    position: 'absolute',
  },
  DotOutStyle: {
    alignSelf: 'center',
    height: scale(20),
    width: scale(20),
    borderRadius: 90,
    borderWidth: 2,
    justifyContent: 'center',
    marginTop: scale(50),
    bottom: scale(20),
  },
  DotInStyle: {
    alignSelf: 'center',
    height: scale(10),
    width: scale(10),
    borderRadius: 90,
  },
  modalContainer: {
    width: '60%',
    backgroundColor: CUSTOM_COLOR.White,
    borderRadius: scale(30),
    height: scale(320),
    overflow: 'hidden',
  },
  modalHeader: {
    width: '100%',
    height: scale(66),
    backgroundColor: CUSTOM_COLOR.BrightGray,
    justifyContent: 'center',
  },
  textHeader: {
    fontSize: scale(23),
    marginLeft: scale(50),
    fontFamily: FONT_FAMILY.PoppinsBold,
  },
  body: {
    width: '70%',
    height: scale(69),
    marginLeft: scale(50),
    marginTop: scale(21),
  },
  textBody1: {
    fontSize: scale(15),
    color: CUSTOM_COLOR.Black,
    opacity: 0.5,
    lineHeight: scale(25),
  },
  textBody2: {
    color: CUSTOM_COLOR.Black,
    fontSize: scale(17),
  },
  cancel: {
    width: scale(110),
    height: scale(50),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: scale(46),
    borderRadius: scale(30),
    position: 'absolute',
    bottom: scale(10),
  },
  cancelText: {
    fontSize: scale(20),
    color: CUSTOM_COLOR.Black,
    fontFamily: FONT_FAMILY.PoppinsBold,
    opacity: 0.5,
  },
  proceed: {
    width: scale(110),
    height: scale(50),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(30),
    backgroundColor: CUSTOM_COLOR.SunsetOrange,
    position: 'absolute',
    bottom: scale(10),
    marginLeft: scale(168),
  },
  proceedText: {
    fontSize: scale(20),
    color: CUSTOM_COLOR.Black,
    fontFamily: FONT_FAMILY.PoppinsBold,
  },
});

export default styles;
